### ISSUE TITLE
Roadmap of v2.0-alpha pre-release

### ISSUE THREAD

**Issue by tngan** [tngan/express-saml2#27]
**Current v1.2.5 will be no longer support after v2.0 is released.**

------- **2.0.0-alpha** -------

- [X] Support Yarn package manager (development)
- [X] Support and run tests in Node v6
- [x] Rewrite and refactor the module using TypeScript v2.0 
  - [X] Basic configuration (tslint, definitions)
  - [x] Rewrite scripts under lib folder
    - [X] Entity.js  
    - [X] SamlLib.js
    - [X] Utility.js
    - [X] urn.js
    - [x] IdPMetadata.js
    - [x] Metadata.js
    - [x] RedirectBinding.js  
    - [x] ServiceProvider.js
    - [x] IdentityProvider.js 
    - [x] PostBinding.js
    - [x] SPMetadata.js 
    - [x] index.js
- [x] API breaking change #13
- [x] Passing test examples 
- [x] Passing test cases
