### ISSUE TITLE
Roadmap to 2.0.0-beta

### ISSUE THREAD

**Issue by tngan** [tngan/express-saml2#41]
**Current v1.4.1 will be no longer support after v2.0 is released.**

------- **2.0.0-beta** -------

## General

- [x] Revamp unit testing (ava)
- [x] Test coverage (nyc) and coverall report.
- [x] Fix travis trigger
- [x] Gitbook removal (move to docsify)

## Issues

- [x] #13 Code revamping - modify api for entity constructor
- [x] #35 Feature - order in xml parser 
- [x] #42 Code revamping - stringify file 
- [x] #43 Code revamping - callback style
- [x] #45 Code revamping - general
- [x] #54 Document - time verification
- [x] #55 Enhancement - recipient should use acl
- [x] #56 Enhancement - attribute customization

## Bug fixes / Others

- [x] Missing base64 encode in unencrypted response 9a24665
- [x] Fix unstable replacement of encrypt assertion 61c5bb8
- [x] Security fix for ejs (one of the dependencies of xml-encryption) f3a968
